server:
  port: 8800

spring:
  application:
    name: base-common-apigateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    metadata-map:
      cluster: apigateway

# 开启Hystrix
feign:
  hystrix:
    enabled: true

# Hystrix 超时设置
hystrix:
  threadpool:
    default:
      coreSize: 500  #并发执行的最大线程数，默认10
  command:
    paas-file:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000  #命令执行超时时间，默认1000ms

# zuul 路由设置
zuul:
  routes:
    api-a:
      path: /api/user/**
      serviceId: buy-user
    api-b:
      path: /api/order/**
      serviceId: buy-order